### ISSUE TITLE
Help with creating an OOk signal

### ISSUE THREAD

**Issue by Crsarmv7l** [triq-org/tx_tools#4]
Hi, 
Thanks for all your great tools, including rtl_433 and this. I was hoping for a little help. I am trying to create a Schrader SMD3MA4 packet. I have figured out how to create the appropriate binary for a SMD3MA4 signal, my issue is trying to use the binary to create the actual signal.

My idea was to use pulse_gen, since SMD3MA4 uses OOK, but I am not quite sure how to structure the file input. Looking at the rtl_433 test file driving_315M_250k in URH, it appears a 0 is silence for ~30us and a 1 is transmission of ~30us. (I basically recreated the binary for that test file)

I did run the test file through rtl_433 with -A but I am not quite sure how to use the short width, long width, etc values in conjunction with your tools.

**Comment by zuckschwerdt** [comment]
If you already have a pulse text then `pulse_gen` is the right tool, otherwise it's pretty low-level.
If you compose the signal from scratch then `code_gen` might be easier.
Have a look at https://github.com/triq-org/tx_tools/blob/master/examples/pmv107j.txt

For Schrader SMD3MA4 the 100us should be 120us, for OOK the `0` should not have a `-40kHz`, and the code would be MC not DMC. Obviously you need to change the payload bytes ;)

**Comment by Crsarmv7l** [comment]
I will give it a try, thank you.

**Comment by Crsarmv7l** [comment]
That worked perfectly. I didn't use MC on the bitstring, because I already manchester encoded it. I certainly understand why there is no lower freq given the OOK. I assume the 120us is based on the short width?

While generating stuff is neat, and a desired end point, I am also trying to understand how/why. If you happen to have any reading that would be beneficial I would appreciate it, my attempts to search haven't been very successful

**Comment by zuckschwerdt** [comment]
120 µs is the "half-bit width" in this protocol. With Manchester coding two half-bit widths encode one data bit.
The "short", "long" convention in rtl_433 is meant for modulations like PWM, PPM, here short=long=120 -- i.e. each (half-)bit is a fixed 120 µs long.

In the end the code_gen instructions are just saying how long to output which frequency, like playing on a musical instrument.

**Comment by Crsarmv7l** [comment]
Thank you. I think I understand. That would mean for Schrader EG53MA4 it would be 123 µs.

Looking at the pmv-107J example and the rtl_433 short/long for the pmv_107j, I think I see how the PWM is working too. 

For toyota it looks like 52 µs for both.

I just need to make sure my deviations are correct.

Thanks again. I really appreciate the feedback!

**Comment by zuckschwerdt** [comment]
Happy to help. There is a summary of modulations/codings on https://triq.org/rtl_433/PULSE_FORMATS.html

**Comment by Crsarmv7l** [comment]
Oh my how naive I was above, not that I am much more knowledgeable now, just enough to know I was way wrong.

Rather than ask you a bunch of questions @zuckschwerdt, is there a discord, telegram, irc or mailing list that I could join and learn from while hopefully asking a question or two here and there?

My latest attempt is to recreate an inFactory signal which I understand to be PWM, which again to my understanding, both 0 and 1 have pulses, the determining factor between a 1 or a 0 is the width of the pulse.

Thank you for the reading as well
